from .auth import TokenManager, InvalidAuthCodeException, ExpiredAuthCodeException, InvalidRedirectURIException
from .api_client import APIClient, FailedRequestException
from .collections import team
BASE_URL = "https://fantasysports.yahooapis.com/fantasy/v2"


class yfsAPI:
    '''
    A class that can be used to easily interface with the Yahoo Fantasy Sports API

    Attributes:
        client_id (str): Client id assigned to the app by Yahoo
        client_secret (str): Client secret assigned to the app by Yahoo
        redirect_uri (str, optional): The uri Yahoo will redirect to upon authorization. Defaults to 'oob' (out of band)
    Methods:
        generate_auth_url(): Creates the url used to prompt the user for authorization
        generate_token(auth_code): Generates a token from the yahoo generated authorization code
    '''
    def __init__(self, client_id, client_secret, redirect_uri='oob'):
        self.redirect_uri = redirect_uri
        self.token_manager = TokenManager(client_id, client_secret, redirect_uri)
        self.api_client = APIClient(base_url=BASE_URL)

    def get_auth_url(self):
        return self.token_manager.auth_url

    def generate_token(self, user_id, auth_code):
        try:
            token = self.token_manager.generate_user_token(user_id, auth_code)
            return {'user_id': user_id, 'token': token}
        except InvalidAuthCodeException as e:
            raise yfsInvalidAuthCodeException(f'invalid auth code: {auth_code}\n\tdetail: auth code does not match code generated by Yahoo') from e
        except InvalidRedirectURIException as e:
            raise yfsInvalidRedirectURIException(f'invalid redirect uri: {self.redirect_uri}\n\tdetail: redirect uri must be \'oob\' or match uri provided to Yahoo') from e
        except ExpiredAuthCodeException as e:
            raise yfsExpiredAuthCodeException(f'expired auth code: {auth_code}:\n\tdetail: auth code has already been used to generate token') from e
        except FailedRequestException as e:
            raise yfsExternalException(f'connection to external server failed: {e.name}') from e

    def get_teams(self, user_id, team_ids=None):
        token = self.token_manager.get_valid_user_token(user_id)
        teams = team.get_teams(token=token, client=self.api_client, team_keys=team_ids)
        return teams

    def get_roster(self, user_id, team_key):
        token = self.token_manager.get_valid_user_token(user_id)
        roster = team.get_roster(token, self.api_client, team_key)
        return roster

    def get_stats(self, user_id, team_key):
        token = self.token_manager.get_valid_user_token(user_id)
        stats = team.get_stats(token, self.api_client, team_key)
        return stats


# Exceptions
class yfsApiException(Exception):
    def __init__(self, msg: str):
        self.msg = msg
        super().__init__(msg)

class yfsAuthException(yfsApiException):
    pass

class yfsInvalidAuthCodeException(yfsAuthException):
    pass

class yfsInvalidRedirectURIException(yfsAuthException):
    pass

class yfsExpiredAuthCodeException(yfsAuthException):
    pass

class yfsExternalException(yfsApiException):
    pass